name: feryouapp
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  hive_flutter: ^1.1.0
  get: ^4.7.2
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  hive_generator: ^1.1.3
  sqflite: ^2.4.1
  path: ^1.9.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  hive: ^2.2.3
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0
  path_provider: ^2.1.5
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background : "#ffffff"
  adaptive_icon_foreground : "assets/icons/icon.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  
  assets:
    - assets/icons/
